[package]
name = "yaxpeax-dis"
version = "0.1.0"
authors = ["iximeow <me@iximeow.net>"]
license = "0BSD"
edition = "2018"
description = "disassembly tool using yaxpeax instruction decoders"

[[bin]]
name = "yaxdis"
path = "src/main.rs"

[dependencies]
clap = "2.33"
hex = "0.4.0"
num-traits = "0.2.10"

# common interfaces for all yaxpeax decoders
yaxpeax-arch = { version = "0.0.3" }

yaxpeax-arm = { version = "0.0.2" }
yaxpeax-mips = { version = "0.0.2" }
yaxpeax-msp430 = { version = "0.0.3" }
yaxpeax-pic17 = { version = "0.0.2" }
yaxpeax-pic18 = { version = "0.0.2" }
yaxpeax-x86 = { version = "0.0.4" }
yaxpeax-m16c = { version = "0.0.2" }
